apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mygocluster
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: mygocontainer
        image: faizan679/myimage:v1
        ports:
        - containerPort: 8080
